mars:
  equatorial_radius_m: 3396190.0
  polar_radius_m: 3376200.0
  crs: "IAU_MARS_2000"
  datum: "D_Mars_2000"

data_sources:
  mola:
    url: "https://astrogeology.usgs.gov/cache/mars/viking/dem/Mars_MGS_MOLA_DEM_mosaic_global_463m.tif"
    resolution_m: 463
  mola_global:
    url: "https://astrogeology.usgs.gov/cache/mars/viking/dem/Mars_MGS_MOLA_DEM_mosaic_global_463m.tif"
    resolution_m: 463
  mola_200m:
    url: "https://astrogeology.usgs.gov/cache/mars/viking/dem/Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif"
    resolution_m: 200
  hirise:
    url: "https://s3.amazonaws.com/mars-hirise-pds/HiRISE_DEMs/"
    resolution_m: 1.0
  ctx:
    url: "https://ode.rsl.wustl.edu/mars/data/ctx/"
    resolution_m: 18.0

logging:
  level: "INFO"
  format: "console"
  file: null

paths:
  data_dir: "data"
  cache_dir: "data/cache"
  output_dir: "data/output"
  spice_kernels: "/usr/local/share/spice"

